### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by claireinez** [liberty-x/twitter#36]
Suspicious-looking commit history - are you still pushing to master?

**Comment by hdrdavies** [comment]
Quite possibly- but this is just to edit the readme if it does occur. Awks :confused::confused:

**Comment by Jbarget** [comment]
is that generally ok for the readme when we're all working in the same room?
a few other times might have been when we're doing a group code review and all see/agree on a change that we know will work. is that still a no no?

**Comment by claireinez** [comment]
Still not okay guys...STOP IT!

And as for the readme, maybe try editing that when you actually commit your code so that you always have an up-to-date record of the project.

**Comment by claireinez** [comment]
Promise you'll stop doing it and I can close this issue.

**Comment by hdrdavies** [comment]
We promise!

**Comment by claireinez** [comment]
Okay... Remember, I _will_ be checking next week!
